openapi: "3.0.3"

info:
    title: "anpi"
    version: "0.0.0"

tags:
    - name: "users"
      description: "ユーザーの操作"
    - name: "auth"
      description: "認証"

components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
                email:
                    type: string
                status:
                    type: string

paths:
    /users:
        get:
            tags:
                - "users"
            summary: "ユーザー一覧を取得"
            description: "ユーザー一覧を取得します"
            responses:
                200:
                    description: "ユーザー一覧"
                    content:
                        application/json:
                            schema:
                                type: "array"
                                items:
                                    $ref: "#/components/schemas/User"
